---
- name: PostgreSQL | Make sure the dependencies are installed
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  with_items: ["python-psycopg2", "python-pycurl", "locales"]

- name: PostgreSQL | Install PostgreSQL
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  with_items:
    - "postgresql"
    - "postgresql-client"
    - "postgresql-contrib"

- name: PostgreSQL | PGTune
  apt:
    name: pgtune
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  when: postgresql_pgtune
