# tasks file for supervisor
---
- include: install.yml
  tags:
    - packages
    - supervisor

- include: configure.yml
  tags:
    - packages
    - supervisor

- include: programs.yml
  tags:
    - packages
    - supervisor

- include: groups.yml
  tags:
    - packages
    - supervisor


- name: Enabled the supervisor service
  service: name=supervisor enabled=yes
  tags: [packages,supervisor]

- name: Start the supervisor service
  service: name=supervisor state=started
  tags: [packages,supervisor]
