---
  - name: Create the application direcotry
    file: path={{application_path}} state=directory owner={{ansible_ssh_user}} group={{ansible_ssh_user}}

  - name: Get application from the repository
    git: >
      repo={{git_repo}}
      dest={{application_path}}
      version={{git_branch}}
      accept_hostkey=yes
    become: no
