---
  - name: Create the application direcotry
    file: path={{application_path}} state=directory owner={{ansible_ssh_user}} group={{ansible_ssh_user}}

  - name: Get application from the repository
    git: >
      repo={{git_repo}}
      dest={{application_path}}
      version={{git_branch}}
      accept_hostkey=yes
    become: no

  - name: Install virtualenv
    pip: name=virtualenv

  - name: Create the virtualenv
    command: virtualenv {{ virtualenv_path }} --no-site-packages
             creates={{ virtualenv_path }}/bin/activate
    become: no

  - name: Ensure gunicorn is installed
    pip: virtualenv={{ virtualenv_path }} name=gunicorn

  - name: Create the virtualenv postactivate script to set environment variables
    template:
      src: virtualenv_postactivate.j2
      dest: "{{ virtualenv_path }}/bin/postactivate"
      mode: 0640
      backup: yes
    become: no

  - name: Create the Gunicorn script file
    template:
      src: gunicorn_start.j2
      dest: "{{ virtualenv_path }}/bin/gunicorn_start"
      mode: 0755
      backup: yes
    become: no

  - name: Install application required by the Django app inside virtualenv
    pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}

  # - name: Run the Django syncdb command
  #   django_manage:
  #     command: syncdb
  #     app_path: "{{ project_path }}"
  #     virtualenv: "{{ virtualenv_path }}"
  #     settings: "{{ django_settings_file }}"
  #   environment: "{{ django_environment }}"
  #   when: run_django_syncdb is defined and run_django_syncdb
  #   tags: django.syncdb

  # - name: Run Django database migrations
  #   django_manage:
  #     command: migrate
  #     app_path: "{{ project_path }}"
  #     virtualenv: "{{ virtualenv_path }}"
  #     settings: "{{ django_settings_file }}"
  #   environment: "{{ django_environment }}"
  #   when: run_django_db_migrations is defined and run_django_db_migrations
  #   tags: django.migrate

  # - name: Run Django collectstatic
  #   django_manage:
  #     command: collectstatic
  #     app_path: "{{ project_path }}"
  #     virtualenv: "{{ virtualenv_path }}"
  #     settings: "{{ django_settings_file }}"
  #   environment: "{{ django_environment }}"
  #   when: run_django_collectstatic is defined and run_django_collectstatic
  #   tags: django.collectstatic
