---
  - name: install git
    apt: name={{ item }} state=installed update_cache=true
    with_items:
      - git
      - git-core
    register: gitinstalled

  - name: setup_git
    when: gitinstalled | success
    shell: git config --global {{ item.command }} "{{item.value}}"
    with_items:
      - {command: user.name, value: "{{git_user_name}}" }
      - {command: user.email, value: "{{git_email}}" }
    become: no
