---
galaxy_info:
  author: "Yaroslav Muravsky"
  license: BSD
  description: Set up the enviroment for Django application in Ubuntu systems
  min_ansible_version: 1.4
  platforms:
   - name: Ubuntu
     versions:
      - precise
      - quantal
      - raring
      - saucy
      - trusty
  categories:
   - web
allow_duplicates: yes

application_name: django_test
application_path: /opt/{{application_name}}
application_static_path: /opt/{{application_name}}/staticfiles
application_media_path: /opt/{{application_name}}/media
virtualenv_path: "{{application_path}}/.env"
setun_nginx: true
